# Generated by Django 4.2.29 on 2026-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('rating_count', models.CharField(default='0', max_length=20)),
                ('age', models.CharField(default='4+', max_length=10)),
                ('rank', models.CharField(default='#1', max_length=10)),
                ('rank_category', models.CharField(blank=True, max_length=100)),
                ('developer', models.CharField(default='68 Media Co.', max_length=200)),
                ('size', models.CharField(default='', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('language', models.CharField(default='English', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
