# Generated by Django 4.2.29 on 2026-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
